post   http://localhost:3000/api/characters HTTP/1.1
Content-Type: application/json

{
  "Stats":{
       "level":{
           "base":3123
       },
            "expirience":0,
            "health":{
                "vitality":"5"
            },
            "mana":{
                "intelect":"200"
            },
            "dmg":{
                "magic":"150",
                "hand":"350"
            }
  },
  "skills":{
      "fire":["321","333","12354"],
      "lightning":["123","4343"],
      "cold":["123","432"]

  }
}
